export const CRISIS_KEYWORDS = {
  critical: [
    'kill myself',
    'killing myself',
    'want to die',
    'wanna die',
    'suicide',
    'suicidal',
    'end my life',
    'ending my life',
    'not worth living',
    'better off dead',
    'cant go on',
    "can't go on",
    'harm myself',
    'harming myself',
    'hurt myself',
    'hurting myself',
    'cut myself',
    'cutting myself',
    'overdose',
    'hang myself',
    'hanging myself',
    'jump off',
    'shoot myself',
    'take my own life',
    'taking my own life',
    'end it all',
    'end it tonight',
    'no reason to live',
    'dont want to be here',
    "don't want to be here",
    'wish i was dead',
    'rather be dead',
    'planned to kill',
    'going to kill myself',
    'gonna kill myself',
  ],
  high: [
    'want to hurt',
    'disappear forever',
    'everyone hates me',
    'hopeless',
    'completely worthless',
    'thinking about ending',
    'nobody would care',
    'nobody would miss me',
    'no one would miss me',
    'cant take it anymore',
    "can't take it anymore",
    'make it stop',
    'no way out',
    'trapped',
    'unbearable pain',
    'pointless',
    'nothing to live for',
    'life is pointless',
    'give up on life',
    'giving up on life',
  ],
  medium: [
    'really depressed',
    'severely depressed',
    'cant get out of bed',
    "can't get out of bed",
    'stopped caring',
    'feeling empty',
    'completely empty',
    'nothing matters',
    'numb inside',
    'feel numb',
    'falling apart',
    'breaking down',
    'lost all hope',
    'no hope',
    'exhausted from existing',
    'tired of everything',
  ],
}

export const CRISIS_RESPONSE_CRITICAL = `I hear you, and I'm deeply concerned about your safety right now. Please reach out immediately:

• **National Suicide Prevention Lifeline**: 988 (call or text, available 24/7)
• **Crisis Text Line**: Text HOME to 741741
• **International Association for Suicide Prevention**: https://www.iasp.info/resources/Crisis_Centres/
• **Emergency Services**: 911 (or your local emergency number)

You don't have to face this alone. These services have trained counselors available 24/7, and they want to hear from you.

Would you like to tell me what's been happening?`

export const EXERCISE_TRIGGER_KEYWORDS = [
  'breathing exercise',
  'breathing technique',
  'help me calm',
  'help me relax',
  'calm me down',
  'calm down',
  'anxiety exercise',
  'coping exercise',
  'meditation',
  'grounding exercise',
  'grounding technique',
  'mindfulness exercise',
  'distract me',
  'i need to calm',
  'help me cope',
  'relaxation exercise',
  'give me an exercise',
  'do an exercise',
  'breathing',
]
